### ISSUE TITLE
Why DaemonSets and not ReplicationControllers?

### ISSUE THREAD

**Issue by area** [ConsenSys/infura#15]
I'm still super new to GCE/kubernetes, so I'm hoping there's a straightforward answer I just haven't spotted yet!

**Comment by hermanjunge** [comment]
Excellent question @area !

If we use `DaemonSet`s, we don't need to worry about the number of `replicas`.

* Everytime we add or delete a `node`, the scheduler will make sure that a pod will be running in that node, provided that the nodes in the cluster had the appropiate `label`, and the `DaemonSet` manifest uses this `nodeSelector`.
* `DaemonSet` ensure us that only one pod will be running per node. Before this kind of resource, we had to rely on _hacks_ involving using hostPort to accomplish that.
